on:
  push:
    branches:
      - master
      - ci-test
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build PDFs
      run: "./mk && ./mk-handout"
    - name: Get version
      id: get_version
      run: |
        version=$(env TZ="Europe/Berlin" date +"%Y-%m-%d-%H.%M.%S")
        echo "version=${version}" >> $GITHUB_OUTPUT
    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{steps.get_version.outputs.version}}
        commit: ${{github.ref}}
        artifacts: "build/talk.pdf,build/talk-handout.pdf"
